#!/bin/bash

#https://www.reddit.com/r/unixporn/comments/6p40ic/volume_notifications_with_dunst/
#https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute



function get_volume {
    amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    if [[ -z "$(command -v dunstify)" ]]; then
        echo "install dunstify to get notifications"
        return
    fi
    volume=`get_volume`
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')
    # Send the notification
    dunstify -i audio-volume-muted-blocking -t 700 -r 2593 -u normal "    $bar"
}

case $1 in
    up)
		# Set the volume on (if it was muted)
        echo "up"
        amixer set Master 5+ &>/dev/null
		send_notification
	;;
    down)
        amixer set Master 5- &>/dev/null
		send_notification
	;;
    mute)

        if is_mute ; then
            amixer set Master unmute &>/dev/null
            dunstify -i audio-volume-muted -t 700 -r 2593 -u normal "Mute"
        else
            amixer set Master mute &>/dev/null
            send_notification
        fi
	;;
esac

# OLD WAY
	# amixer -D pulse set Master on > /dev/null
	# amixer -D pulse sset Master 5%+ > /dev/null
	# amixer -D pulse set Master on > /dev/null
	# amixer -D pulse sset Master 5%- > /dev/null
	# amixer -D pulse set Master 1+ toggle > /dev/null
