#!/bin/bash

platform="linux"
if [[ "$1" == "all" ]]; then
    platform=".*"
    shift
fi

if [[ -n "$2" ]]; then
    platform="$1"
    shift
fi

types="(tar.gz|tar.xz|deb|7z|zip|tar.bz2|bz2|rar|gz|tar|tbz2|tgz|Z|tar.zst)"


info=$(echo "$1" | cut -d / -f 4,5)
author=$(echo "$info" | cut -d / -f 1)
repo=$(echo "$info" | cut -d / -f 2)

versions=$(wget -q https://api.github.com/repos/${author}/${repo}/releases/latest -O - |
	awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' |
    grep "$platform" | grep -E "$types")

source_code_tag=$(wget -q https://api.github.com/repos/${author}/${repo}/releases/latest -O - |
	awk -F \" -v RS="," '/tag_name/ {print $(NF-1)}')

if [[ "$versions" != "" || "$source_code_tag" != "" ]]; then
    chosen="$(fzf --no-preview -d / --with-nth -1 <<< "$(echo -e "${versions}\ntag: $source_code_tag.zip\ntag: $source_code_tag.tar.gz" | sed 's/^$//g' )")"
    echo "$chosen"
    exit
fi

echo "$versions"
echo "$source_code_tag"
