#!/bin/bash

file_name=$1
source=$2
destination="${3:-.}"

_file() {
  # shellcheck disable=SC2086
  dirs=$(find -L $1 -maxdepth 1 -type d 2>/dev/null | tail -n +2)

  dirs_files=""
  for f in $dirs; do
    dirs_files+="$f $(basename "$f")\n"
  done
  dirs_files=$(echo -e "$dirs_files")
  file=$(echo "$dirs_files" | fzf --with-nth 2 --height=75% --preview="[[ ! -f {1}/$file_name ]] && echo '\"{2}\" has sub-directories' || (bat --color always {1}/$file_name)" --preview-window="80%:wrap")
  echo "$file"
}

folder_file=$(_file "$source")
folder="$(echo "$folder_file" | awk '{print $1}')"
file="$(echo "$folder_file" | awk '{print $2}')"


[ -z "$file" ] && exit

while [[ ! -f "$folder/$file_name" ]]; do
  folder_file=$(_file "$folder")
  folder="$(echo "$folder_file" | awk '{print $1}')"
  file="$(echo "$folder_file" | awk '{print $2}')"
	if [[ -z $file ]]; then
		exit
	fi
done
#
[[ "$destination" != "." && ! -d "$destination" ]] &&
	mkdir "$destination"

if [[ ! -f "$folder/$file_name" ]]; then
  exit
fi

cp "$folder/$file_name" "$destination"
echo -e "\e[35mcopied $file_name"

if [[ -f "$folder/.env" ]]; then
  cp "$folder/.env" .
  echo -e "\e[35mcopied .env file"
fi

