#!/bin/bash
# getfile unique

# creating a getfile multiple should be fairly easy
# look at the mkfile script for inspiration

folder=$1
destination="${2:-.}"
destination_env="${3:-.}"

options=$(find "$folder" -mindepth 1 -not -name '.*' -type d)
chosen=$(fzf -d / --with-nth -1 --preview="bat {}/* --color=always" <<< "$options")

[[ ! -d "$chosen" ]] && exit

cp ${chosen}/* "$destination"
cp "$chosen/.env" "$destination_env"
