#!/bin/bash


folder_chosen="${1:-$UTILITIES}"
destination="${2:-.}"

final_=""
files_chosen=""
additional_folders=""
IFS=$'\n'
count=0
while true; do
    all_files=1
    for folder in $folder_chosen; do
        if [[ ! -d "$folder" ]]; then
            continue
        fi
        files_chosen=""
        content=$(find "$folder" -mindepth 1 -maxdepth 1 -name "*" -printf "%T+\t%p\n" | sort -r | awk '{print $2}')
        files_chosen="$(fzf -m --prompt "file: " -d / --with-nth -1 --preview="ls {} --color=always" <<< "$content")"

        if [[ -z "$files_chosen" ]]; then
            exit 1
        fi

        for f in $files_chosen; do
            if [[ ! -d $f ]]; then
                final_+="$f\n"
            else
                all_files=0
            fi
        done
        additional_folders=$files_chosen

    done

    folder_chosen="$additional_folders"
    additional_folders=""
    if [[ $all_files == 1 ||  -z "$files_chosen" ]]; then
        break
    fi
done

for f in $(echo -e "$final_"); do
    cp "$(echo -e "$f")" "$destination"
done
