#!/bin/bash

file_name=$1
folder=$2
destination="${3:-.}"

files=$(find -L $folder -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
file=$(echo "$files" | fzf --height=75% --preview="[[ ! -f $folder/{}/$file_name ]] && echo '\"{}\" has sub-directories' || (bat --color always $folder/{}/$file_name)" --preview-window="90%:wrap")
env_file="$folder/$file/.env"


[ -z "$file" ]  && exit

path="$folder/$file"
while [[ ! -f "$path/$file_name" ]]; do
    files=$(find -L $path -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
    file=$(echo $files | fzf --height=75% --preview="bat --color always $path/{}/$file_name" --preview-window="90%:wrap")
    if [[ -z $file ]]; then
        exit
    fi
    path="$path/$file"
    env_file="$path/$file/.env"
done

[[ "$destination" != "." && ! -d "$destination" ]] \
    && mkdir "$destination"

if [[ -f "$path/$file_name"  ]]; then
    cp "$path/$file_name" "$destination" 
    echo -e "\e[35mcopied $file_name"
else 
    cp "$folder/$file/$file_name" "$destination"
    echo -e "\e[35mcopied $file_name"
fi

if [[ "$file_name" != ".env" && -f "$env_file" ]]; then
    echo -e "\e[35mcopied .env file"
    cp "$env_file" .
fi
