#!/bin/bash

file_name="launch.json"
folder=$FILES/project_configs/launch
destination=".vscode/"

files=$(find $folder -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
file=$(echo "$files" | fzf --height=75% --preview="[[ ! -f $folder/{}/$file_name ]] && echo '\"{}\" has sub-directories' || (bat --color always $folder/{}/$file_name)" --preview-window="90%:wrap")
env_file="$folder/$file/.env"


[ -z "$file" ]  && exit

path="$folder/$file"
while [[ ! -f "$path/$file_name" ]]; do
    files=$(find $path -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
    file=$(echo $files | fzf --height=75% --preview="bat --color always $path/{}/$file_name" --preview-window="90%:wrap")
    if [[ -z $file ]]; then
        exit
    fi
    path="$path/$file"
    env_file="$path/$file/.env"
done

[[ ! -d "$destination" ]] \
    && mkdir "$destination"

[[ -f "$path/$file_name"  ]] \
    &&  cp "$path/$file_name" "$destination" \
    || cp "$folder/$file/$file_name" "$destination"

[[ -f "$env_file" ]] \
    && cp "$env_file" .
