#!/usr/bin/env python

from __future__ import print_function
from optparse import OptionParser
import os
import sys
import re

parser = OptionParser()

parser.add_option("-i", "--import", dest="imports", action="append", default=[],
                  help="Import package of given name", metavar="PACKAGE")

parser.add_option("-m", "--main", dest="main", action="store_true", default=False,
                  help="Wrap input in a func main() {} block")

parser.add_option("-d", "--debug", dest="debug", action="store_true", default=False,
                  help="Print the generated Go code instead of running it.")

(options, args) = parser.parse_args()

stdin = ""
for line in sys.stdin.readlines():
    stdin += "%s\n" % line

out = ""

reg = r"^package .+$"
if not re.match(reg, stdin.split("\n")[0]):
    out += "package main\n\n"

for package in options.imports:
    out += "import \"%s\"\n" % package

out += "\n"
if options.main:
    out += "func main() {\n%s\n}\n" % stdin
else:
    out += stdin

if options.debug:
    print(out)
else:
    tmpfile = "/%s/%s" % ("tmp", "tmp_gos.go")
    f = open(tmpfile, 'w')
    print(out, file=f)
    f.close()
    os.system("go run " + tmpfile)
