#!/bin/zsh

# Config locations
GENERAL_PATH="${DOTFILES:-~/.dotfiles}/general/.config"
NVIM_PATH="${DOTFILES:-~/.dotfiles}/nvim/.config/nvim"
ZSH_PATH="${DOTFILES:-~/.dotfiles}/zsh/.config/zsh"
folders="$GENERAL_PATH/shortcuts/sd"
files="$GENERAL_PATH/shortcuts/sf"

# Output locations
shellrc="$ZSH_PATH/.zshrc"
shell_shortcuts="$ZSH_PATH/.auto_aliases"
ranger_shortcuts="$GENERAL_PATH/ranger/shortcuts.conf"
nvim_shortcuts="$NVIM_PATH/lua/shortcuts.lua"

# Remove
rm -f "$shell_shortcuts" "$ranger_shortcuts" "$nvim_shortcuts"

#source them if not sourced
(grep "\. \$ZDOTDIR/.auto_aliases"  $shellrc)>/dev/null \
    || echo '[[ -f "$ZDOTDIR/.auto_aliases" ]] && . $ZDOTDIR/.auto_aliases' >> $shellrc

(grep "source $ranger_shortcuts" $GENERAL_PATH/ranger/rc.conf)>/dev/null \
    || echo "source $ranger_shortcuts" >> $GENERAL_PATH/ranger/rc.conf


# escape single quotes like this: 'sample'\'' end' --> sample's end

shell_dir='{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "alias "$1"='\''cd "shortcut" && ls -a'\''"}'
ranger_dir='{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut" "$i; else shortcut=$i}; {print "map <backspace>"$1" cd "shortcut"\nmap t"$1" tab_new "shortcut"\nmap m"$1" shell mv -v %s "shortcut"\nmap Y"$1" shell cp -rv %s "shortcut}'

# neovim dir
basic='{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print"'
change_dir='vim.keymap.set(\"n\", \"<localleader>"$1"\", \"<cmd>e "shortcut"<cr>\", {silent=true, noremap=true})\n'
telescope='vim.keymap.set(\"n\",\"<localleader>,"$1"\", \":lua require('\''telescope.builtin'\'').find_files({prompt_title = '\''<"shortcut">'\'', cwd = '\''"shortcut"'\''})<cr>\", { noremap = true, silent = true })'
telescope_grep='vim.keymap.set(\"n\",\"<localleader>;"$1"\", \":lua require('\''telescope.builtin'\'').live_grep({prompt_title = '\''<"shortcut">'\'', cwd = '\''"shortcut"'\''})<cr>\", { noremap = true, silent = true })'
end='"}'

# directory shortcuts
sed "/^#/d; /^$/d" $folders | tee \
    >(awk "$shell_dir" >> $shell_shortcuts) \
    >(envsubst | awk "$ranger_dir" >> $ranger_shortcuts) \
    >(awk  "$basic$change_dir$telescope$telescope_grep$end" >> "$nvim_shortcuts") >/dev/null

# tmux
sed "/^#/d; /^$/d" $folders | tee >(envsubst | awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut" "$i; else shortcut=$i}; {print "map <backspace2>"$1" cd "shortcut"\nmap t"$1" tab_new "shortcut"\nmap m"$1" shell mv -v %s "shortcut"\nmap Y"$1" shell cp -rv %s "shortcut}' >> $ranger_shortcuts) >/dev/null
# envsubst changes $HOME -> /home/myuser


# dotfile shortcuts
sed "/^#/d; /^$/d" $files |tee \
    >(awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "alias "$1"=\"$EDITOR "shortcut"\""}' >> $shell_shortcuts) \
    >(envsubst | awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "map <backspace>"$1" shell $EDITOR "shortcut}' >> $ranger_shortcuts) \
    >(awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "vim.keymap.set(\"n\", \"<localleader>"$1"\", \"<cmd>e "shortcut" <cr>\", {silent=true, noremap=true})"}' >> "$nvim_shortcuts") >/dev/null
