#!/bin/zsh

# Config locations
GENERAL_PATH="${DOTFILES:-~/.dotfiles}/general/.config"
NVIM_PATH="${DOTFILES:-~/.dotfiles}/nvim/.config/nvim"
ZSH_PATH="${DOTFILES:-~/.dotfiles}/zsh/.config/zsh"
folders="$GENERAL_PATH/shortcuts/sd"
files="$GENERAL_PATH/shortcuts/sf"

# Output locations
shellrc="$ZSH_PATH/.zshrc"
shell_shortcuts="$ZSH_PATH/.auto_aliases"
ranger_shortcuts="$GENERAL_PATH/ranger/shortcuts.conf"
lf_shortcuts="$GENERAL_PATH/lf/shortcuts"
nvim_shortcuts="$NVIM_PATH/lua/shortcuts.lua"

# Remove
rm -f "$shell_shortcuts" "$ranger_shortcuts" "$nvim_shortcuts" "$lf_shortcuts"

#source them if not sourced
(grep "\. \$ZDOTDIR/.auto_aliases"  $shellrc)>/dev/null \
    || echo '[[ -f "$ZDOTDIR/.auto_aliases" ]] && . $ZDOTDIR/.auto_aliases' >> $shellrc

(grep "source $ranger_shortcuts" $GENERAL_PATH/ranger/rc.conf)>/dev/null \
    || echo "source $ranger_shortcuts" >> $GENERAL_PATH/ranger/rc.conf

(grep "source $lf_shortcuts" $GENERAL_PATH/lf/lfrc)>/dev/null \
    || echo "source $lf_shortcuts" >> $GENERAL_PATH/lf/lfrc


# escape single quotes like this: 'sample'\'' end' --> sample's end

shell_dir='{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "alias "$1"='\''cd "shortcut" && ls -a'\''"}'
ranger_dir='{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut" "$i; else shortcut=$i}; {print "map <backspace>"$1" cd "shortcut"\nmap t"$1" tab_new "shortcut"\nmap m"$1" shell mv -v %s "shortcut"\nmap Y"$1" shell cp -rv %s "shortcut}'
lf_dir='{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut" "$i; else shortcut=$i}; {print "map <backspace2>"$1" cd "shortcut"\nmap m"$1" $ mv -v $f "shortcut"\nmap Y"$1" $ cp -rv $f "shortcut}'

# neovim dir
basic='{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print"'
change_dir='vim.keymap.set(\"n\", \"<backspace>"$1"\", \"<cmd>e "shortcut"<cr>\", {silent=true, noremap=true})\n'
telescope='vim.keymap.set(\"n\",\"<backspace><a-p>"$1"\", \":lua require('\''telescope.builtin'\'').find_files({prompt_title = '\''<"shortcut">'\'', cwd = '\''"shortcut"'\'', hidden = '\''true'\''})<cr>\", { noremap = true, silent = true })\n'

# this uses live_grep
# telescope_grep='vim.keymap.set(\"n\",\"<localleader>tl"$1"\", \":lua require('\''telescope.builtin'\'').live_grep({prompt_title = '\''<LIVE GREP "shortcut">'\'', cwd = '\''"shortcut"'\''})<cr>\", { noremap = true, silent = true })\n'

# this uses grep_string
# you can exact match using a single quote
# https://github.com/nvim-telescope/telescope-fzf-native.nvim
telescope_grep='vim.keymap.set(\"n\",\"<backspace><a-r>"$1"\", \":lua require('\''telescope.builtin'\'').grep_string({prompt_title = '\''<LIVE GREP "shortcut">'\'', cwd = '\''"shortcut"'\'', search ='\'''\'',  shorten_path = true})<cr>\", { noremap = true, silent = true })\n'
end='"}'

# directory shortcuts
sed "/^#/d; /^$/d" $folders | tee \
    >(awk "$shell_dir" >> $shell_shortcuts) \
    >(envsubst | awk "$ranger_dir" >> $ranger_shortcuts) \
    >(envsubst | awk "$lf_dir" >> $lf_shortcuts) \
    >(awk  "$basic$change_dir$telescope$telescope_grep$end" >> "$nvim_shortcuts") >/dev/null

# tmux
# put the ones for tmux here
# envsubst changes $HOME -> /home/myuser


# dotfile shortcuts
sed "/^#/d; /^$/d" $files |tee \
    >(awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "alias "$1"=\"$EDITOR "shortcut"\""}' >> $shell_shortcuts) \
    >(envsubst | awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "map <backspace>"$1" shell $EDITOR "shortcut}' >> $ranger_shortcuts) \
    >(envsubst | awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "map <backspace2>"$1" $ $EDITOR "shortcut}' >> $lf_shortcuts) \
    >(awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "vim.keymap.set(\"n\", \"<backspace>"$1"\", \"<cmd>e "shortcut" <cr>\", {silent=true, noremap=true})"}' >> "$nvim_shortcuts") >/dev/null
