#!/bin/bash

default="go"
ext="${1:-$default}"
playHome="/tmp/${ext}"
_file="main.$ext"
sessionName="play-$ext" 

mkdir -p "$playHome" &>/dev/null

if ! tmux has-session -t "$sessionName" 2>/dev/null; then
  tmux -f ~/.config/tmux/tmux.conf \
    -u new -A -s "$sessionName" -c "$playHome" -d

  tmux send-keys -t "$sessionName" "nvim $_file" Enter
fi

if [[ -z $TMUX ]]; then
  tmux attach -t "$sessionName" 2>/dev/null
else
  tmux switch-client -t "$sessionName" 2>/dev/null
fi


