#!/bin/bash

# can be migrated to using json by just changing the yq to jq
# example config:
# name:
#   book: book_path
#   project: project_path

in_shell=true
while getopts "d" arg; do
    case "$arg" in
        d)
            # opened using sxhkd
            in_shell=false;
            ;;
        *)
            echo "flag not supported" && exit;
            ;;
    esac
done

config_file="$HOME/.cache/.bookpractice.yml";
[[ ! -f "$config_file" ]] && touch "$config_file";

names="$(yq -r 'keys | .[]' "$config_file")"
if [ -z "$names" ]; then
    notify-send "no practice books found in $HOME/.cache/.bookpractice.yml";
    exit 1
fi
name="$(dmenu -p "book practice: " <<< "$names")";
[ -z "$name" ] && exit
book="$(yq -r ".$name | .book " "$config_file" | envsubst)";
project="$(yq -r ".$name | .project " "$config_file" | envsubst)";

setsid zathura "$book" &
if "$in_shell"; then
    cd "$project" || exit;
    tmux -u -f ~/.config/tmux/tmux.conf new -d -s "$name" 
    tmux send-keys -t  "$name" "nvim ." Enter;
    exec tmux attach-session -t "$name"
else
    setsid "$TERMINAL" -e \
        bash -c "cd $project && 
        tmux -u -f ~/.config/tmux/tmux.conf new -d -s $name
        tmux send-keys -t  $name 'nvim .' Enter;
        tmux attach-session -t $name"
fi 
