#!/bin/bash

in_shell=true
while getopts "d" arg; do
    case "$arg" in
        d)
            # opened using sxhkd
            in_shell=false;
            ;;
        *)
            echo "flag not supported" && exit;
            ;;
    esac
done

config_file="$HOME/.cache/.bookpractice.json";
[[ ! -f "$config_file" ]] && touch "$config_file";

names="$(jq -r 'keys | .[]' "$config_file")"
name="$(dmenu <<< "$names")";

book="$(jq -r ".$name | .book " "$config_file" | envsubst)";
project="$(jq -r ".$name | .project " "$config_file" | envsubst)";


setsid zathura "$book" &
if "$in_shell"; then
    cd "$project" || exit
    tmux -u -f ~/.config/tmux/tmux.conf new -A -s "$name" 
else
    setsid "$TERMINAL" -e \
        bash -c \
        "cd $project &&
        tmux -u -f ~/.config/tmux/tmux.conf new -A -s $name" &
fi
tmux -u -f ~/.config/tmux/tmux.conf send-keys -t  "$name" "nvim ." Enter;
