#!/bin/bash
NOTES="${NOTES:-$HOME/notes}"
name="$(date +%d%m%Y).md"
# more than 20 days, save to archive
time_limit_to_archive="+20"

save_in_archive_old_notes() {
    find "$NOTES" -mindepth 1 -not -path '*/.archive/*' -type d -mtime "$time_limit_to_archive" | xargs -n1 -I{} mv {} "$NOTES/.archive/"
}

if [[ ! -d "$NOTES/.archive" ]]; then
    mkdir -p "$NOTES/.archive"
fi

save_in_archive_old_notes

if [[ $1 != "list" ]]; then
    subject="$1"
fi

fzfd=0
if [[ -z "$subject" ]]; then
    subject=$(echo -e "$(find "$NOTES" -mindepth 1 -type d)\nnew" | fzf --delimiter / --with-nth -1 --preview="[ -d {} ] && ls {} --color=always || chafa $FILES/fun/kaguya.jpg --stretch")
    fzfd=1
fi

if [[ $subject == "dmenu" ]]; then
    subject=$(echo -e "$(find "$NOTES" -mindepth 1 -type d -printf '%f\n')\nnew" | dmenu 2>/dev/null )
    if [[ $subject == "new" ]]; then
        st -e nvim "$NOTES" 
        exit
    fi
fi

if [[ $1 == "list" ]]; then
    [[ -z "$subject" ]] && exit
    chosen_file=$(find "$subject" -mindepth 1 -type f -printf '%f\n' | fzf --preview="bat $subject/{} --color=always")
    if [[ -n "$chosen_file" ]]; then
        nvim "$subject/$chosen_file"
    fi
    exit
fi

if [[ $subject == "new" ]]; then
    echo -e "\e[35mEnter new subject"
    read -r subject
fi

[[ -z "$subject" ]] && exit


retrieve_notes_from_archive() { 
    find "$NOTES/.archive" -name "$1" -type d
}
# check if subject is in archive
notes_in_archive="$(retrieve_notes_from_archive "$subject")"
if [[ -n $notes_in_archive ]]; then
    mv "$notes_in_archive" "$NOTES"
fi

if [[ $fzfd == 1 ]]; then
    path="$subject"
else
    path="$NOTES/$subject"
fi

if [[ ! -d "$path" ]]; then
    mkdir -p "$path"
fi

nvim "$path/$name"


