#!/bin/sh

_file="$(rg --color=always --line-number --no-heading --smart-case "${@:-^[^\n]}" \
    | fzf -d ':' --preview 'bat --style=numbers --color=always $(cut -d: -f1 <<< {1}) --highlight-line {2}' \
    --preview-window='50%' --with-nth 1,3.. --exact)"

_file="${_file%%:*}"
[ -z "$_file" ] && exit
exec nvim "$_file"
