#!/bin/bash

if [ -z "$1" ]; then
    echo -e "\e[31mno pattern given..."
    exit 1
fi
rg "$1" "$WIKI/notes/"
file_="$(rg -l "$1" "$WIKI/notes/" | fzf --with-nth -2,-1 --delimiter / --no-preview --no-preview --layout=default --height='1%' --margin='0%')"
if [ -z "$file_" ]; then
    exit 1
fi
nvim "$file_"
