#!/usr/bin/env bash

selected="${1:-}"
depth="${2:-1}"
manual=0

fzf_with_nth() {
	[[ -z $depth ]] && echo "-2,-1" && return

	value=""
	for i in $(seq "$depth" -1 1); do
		if [[ $i != 1 ]]; then
			value+="-$i,"
		else
			value+="-$i"
		fi
	done
	echo "$value"
}

folders=("$WORK" "$PROJECTS" "$CODE" "$LEARN" $REPOS/*)
folders_result=""
if [[ -z "$selected" ]]; then
	# the -not -path is to ignore hidden folders
	# find_args=(-L "${folders[@]}" -mindepth 1 -maxdepth 1 -not -path '*/\.*' -type d -printf "%T@ %Tc %p\n")
	for f in "${folders[@]}"; do
		find_args=(-L "$f" -mindepth 1 -maxdepth 1 -not -path '*/\.*' -type d -printf "%T@ %Tc %p\n")
		if [[ -n $folders_result ]]; then
			folders_result="${folders_result}\n$(find "${find_args[@]}" | sort -nr | awk '{print $NF}')"
		else
			folders_result="$(find "${find_args[@]}" | sort -nr | awk '{print $NF}')"
		fi
	done
	selected=$(echo -e "$folders_result" | fzf --preview="ls {} --color=always" --delimiter / --with-nth -2,-1 --preview-window=60%:wrap | awk '{print $NF}')
else
	manual=1
	with_nth=$(fzf_with_nth)
	find_args=(-L "$selected" -mindepth "$depth" -maxdepth "$depth" -not -path '*/\.*' -type d -printf "%T@ %Tc %p\n")
	folders_result="$(find "${find_args[@]}" | sort -nr | awk '{print $NF}')"
	selected=$(echo -e "$folders_result" | fzf --preview="ls {} --color=always" --delimiter / --with-nth "$with_nth" --preview-window=60%:wrap | awk '{print $NF}')
fi

[[ -z $selected ]] && exit 0

if [[ $manual == 1 ]]; then
	tmux-sessionizer "$selected" "$(basename $selected)"
	exit 0
fi

declare -A types=(["work"]="$WORK" ["projects"]="$PROJECTS" ["code"]="$CODE" ["learn"]="$LEARN")
selected_name=$(basename "$selected" | tr . _)
for key in "${!types[@]}"; do
	if grep -o "/$key/" <<<"$selected" &>/dev/null; then
		prefix="${key:0:1}"
	fi
done
noprefix=0
[[ -z $prefix ]] && noprefix=1

if [[ $noprefix == 1 ]]; then
	tmux-sessionizer "$selected" "$selected_name"
else
	tmux-sessionizer "$selected" "$prefix-$selected_name"
fi
