#!/usr/bin/env bash

selected="${1:-}"
depth="${2:-1}"
manual=0

fzf_with_nth() {
    [[ -z $depth ]] && echo "-2,-1" && return

    value=""
    for i in $(seq "$depth" -1 1); do
        if [[ $i != 1 ]]; then 
            value+="-$i,"
        else
            value+="-$i"
        fi
    done
    echo "$value"
}

folders=($WORK $PROJECTS $PLAYGROUND/code $LEARN $REPOS/*)
if [[ -z "$selected" ]]; then
    # the -not -path is to ignore hidden folders 
    selected=$(find -L ${folders[@]}  -mindepth 1 -maxdepth 1 -not -path '*/\.*' -type d | fzf --preview="ls {} --color=always" --delimiter / --with-nth -2,-1 --preview-window=60%:wrap)
else
    manual=1
    with_nth=$(fzf_with_nth)
    selected=$(find -L $selected -mindepth $depth -maxdepth $depth -not -path '*/\.*' -type d | fzf --preview="ls {} --color=always" --delimiter / --with-nth $with_nth --preview-window=60%:wrap)
fi

[[ -z $selected ]] && exit 0

if [[ $manual == 1 ]]; then
    tmux-sessionizer "$selected" "$(basename $selected)" 
    exit 0
fi

declare -A types=(["work"]="$WORK" ["project"]="$PROJECTS" ["code"]="$PLAYGROUND/code"  ["learn"]="$LEARN")
selected_name=$(basename "$selected" | tr . _)
for key in "${!types[@]}"; do
    if grep -o "/$key/" <<< "$selected"; then
        prefix="${key:0:1}"
    fi
    prefix=${key:0:1}
done

tmux-sessionizer "$selected" "$prefix-$selected_name" 
