#!/bin/bash

folder_name="${1:-$(pwd)}"
session_name="${2:-"$(basename "$(pwd)")"}"


if [[ "$session_name" =~ ^. ]]; then
    session_name="${session_name/./}"
fi

# is running but no session with that name
if ! tmux has-session -t="$session_name" 2> /dev/null; then
    # tmux running but no session with this name, create it
    echo "second"
    tmux -f ~/.config/tmux/tmux.conf new-session -ds "$session_name" -c "$folder_name"
fi

if [[ -z $TMUX ]]; then 
    tmux attach -t "$session_name"
else
    tmux switch-client -t "$session_name" 2> /dev/null
fi
