#!/bin/bash

search_dir="${1:-.}"

FZF_DEFAULT_COMMAND="fd --follow --hidden -t f . $search_dir"
cmd="fzf --bind 'tab:reload(fd -uuu --follow --hidden . $search_dir)' --preview 'if file {} | grep -i -q 'directory'; then ls --color {}; else if file {} | grep -i -q 'text'; then bat --color always {}; else echo \"{} is a binary file\"; fi; fi'"
name="$(eval $cmd)"
if [[ -z $name ]]; then 
  return
fi

if [[ -d $name ]]; then
    cd "$name" || return
    return
fi

[ -n "$name" ] &&
nvim "$name"
