#!/bin/bash

# show only text files

FZF_DEFAULT_COMMAND="fd --follow  --hidden -t f"
cmd="fzf --bind 'tab:reload(fd -uuu --follow --hidden)' --preview 'if file {} | grep -i -q 'directory'; then ls --color {}; else echo \"{} is a binary file\"; fi'"
name="$(eval $cmd)"
if [[ -z $name ]]; then 
  return
fi

if [[ -d $name ]]; then
    cd "$name" || return
    return
fi

[ -n "$name" ] &&
nvim "$name"

# if [[ -z $1 ]]; then
# 	name=$(fzf -d / --with-nth -5,-4,-3,-2,-1 --preview-window=60%:wrap)
# 	[ -n "$name" ] && exec nvim "$name"
#     exit
# fi
#
# if [[ -d $1 ]]; then
#     FZF_DEFAULT_COMMAND="fd --type f  --search-path $1 --follow --hidden -x grep -Il . {}"
#
#     name=$(fd . "$1" | fzf -d / --with-nth -5,-4,-3,-2,-1 --preview-window=60%:wrap)
#     [ -n "$name" ] && exec nvim "$name"
# else
#     name=$(fzf --query "$1")
#     [ -n "$name" ] && exec nvim "$name"
# fi
