#!/bin/bash

FZF_DEFAULT_COMMAND="fd --type d --follow --hidden"
if [ -z "$1" ]; then
	name=$(fzf --preview 'ls {} --color=always')
	[ -n "$name" ] && cd "$name"
else
    if [ -d "$1" ]; then
		FZF_DEFAULT_COMMAND="fd --type d --search-path $1 --follow --hidden"
		name=$(fzf -d / --with-nth -5,-4,-3,-2,-1 --preview 'ls {} --color=always')
		[ -n "$name" ] && cd "$name"
	fi
fi
