#!/bin/bash

# show only text files
FZF_DEFAULT_COMMAND="fd --type f --follow  --hidden "

if [[ -z $1 ]]; then
	name=$(fzf)
	[ -n "$name" ] && exec nvim "$name"
    exit
fi

if [[ -d $1 ]]; then
    FZF_DEFAULT_COMMAND="fd --type f  --search-path $1 --follow --hidden -x grep -Il . {}"

    name=$(fd . "$1" | fzf -d / --with-nth -2,-1)
    [ -n "$name" ] && exec nvim "$name"
else
    name=$(fzf --query "$1")
    [ -n "$name" ] && exec nvim "$name"
fi
