-- vim.cmd([[
--     :let maplocalleader = '\<BS>'
-- ]])
-- vim.g.maplocalleader="/"
-- vim.api.nvim_set_keymap('n', '<leader>n', ':echo "test leader"', {} )
-- vim.api.nvim_set_keymap('n', '<localleader>n', ':echo "test localleader"', {} )
