#!/bin/bash
# set -xe
# path="$WIKI/cheatsheets"
# folder=$(ls $path  | dmenu -i -p "choose")
# path="${path}/${folder}/${folder} cheatsheet.pdf"
# zathura "$path"

_path="$WIKI/cheatsheets"
folder=$(ls "$_path"  | dmenu -i -p "Cheatsheet:" -fn "$DEFAULT_DMENU_FONT" -n)
if [[ -z $folder ]]; then
    exit
fi
files=$(ls "${_path}/${folder}/")
echo "$files" | wc -l
if [[ $(echo "$files" | wc -l ) == 1 ]]; then
    filePath="${_path}/${folder}/$files"
    echo  "$filePath"
    echo  "$filePath" | "$AUTOMATION/open_with"
    exit
fi

file=$(echo "$files" | dmenu -i -p "Cheatsheet:" -fn "$DEFAULT_DMENU_FONT" -n)
filePath="${_path}/${folder}/$file"
if [[ -z $file ]]; then
    exit
fi

echo  "$filePath" | "$AUTOMATION/open_with"
