#!/bin/bash

_path="$1"
worktree_data=$(git worktree list --porcelain | grep -A2 "$_path")
commit_id="$(head -2 <<<"$worktree_data" | tail -1 | awk '{print $2}')"
branch="$(tail -1 <<<"$worktree_data")"

if [[ "$branch" == "detached" ]]; then
	echo -e "\e[31mDETACHED HEAD"
fi

git log --decorate --oneline --color=always "$commit_id"
