#!/bin/bash
WIKI=${WIKI:-"$HOME/.local/share/wiki/"}
files=$(fd '.' $WIKI -t f -e org)

if getopts 'd' flag; then
  case "${flag}" in
    d) chosen_file=$(echo -e "$files\ncreate" | xargs -I {} basename {} .org | dmenu -n) ;;
  esac
else
    chosen_file=$(echo -e "$files\ncreate" | xargs -I {} basename {} .org | fzf)
fi


# chosen_file=$(echo -e "$files\ncreate" | xargs -I {} basename {} .org | dmenu -n)

if [[  $chosen_file == "create" ]]; then
    st -e nvim $WIKI/notes/
    exit 0
fi

chosen_filepath=$(echo "$files" | grep "/${chosen_file}.org" 2>/dev/null)

if [[  -n $chosen_filepath ]]; then
    if [[ $flag == '?' ]]; then
        nvim $chosen_filepath
    else
        st -e nvim $chosen_filepath 2>/dev/null
    fi
    
fi
