vim.keymap.set("n", "<localleader>H", "<cmd>cd ~ <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>d.", "<cmd>cd ~/.dotfiles <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>uu", "<cmd>cd $REMOTES <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>n.", "<cmd>cd $NOTES <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>wo", "<cmd>cd $WORK <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>bk", "<cmd>cd $BOOKS <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>bK", "<cmd>cd $BOOKS/ln <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>ln", "<cmd>cd $BOOKS/ln <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>ba", "<cmd>cd $BACKUPS <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>ll", "<cmd>cd $LEARN <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>l.", "<cmd>cd $LEARN <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>T.", "<cmd>cd $TRASH <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Tt", "<cmd>cd $TRASH <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Tr", "<cmd>cd $HOME/Downloads/torrents <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>sk", "<cmd>cd $SUCKLESS <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>f.", "<cmd>cd $XDG_CONFIG_HOME <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>v.", "<cmd>cd $XDG_CONFIG_HOME/nvim <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vl", "<cmd>cd $XDG_CONFIG_HOME/nvim/lua/lsp <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>va", "<cmd>cd $XDG_CONFIG_HOME/nvim/lua/config/automation <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vc", "<cmd>cd $XDG_CONFIG_HOME/nvim/lua/core <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vC", "<cmd>cd $XDG_CONFIG_HOME/nvim/lua/config <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vu", "<cmd>cd $XDG_CONFIG_HOME/nvim/lua/utils <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vk", "<cmd>cd $XDG_CONFIG_HOME/nvim/lua/config/keybindings <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>sp", "<cmd>cd ~/.config/nvim/my_snippets <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>m.", "<cmd>cd $SCRIPTS <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>F.", "<cmd>cd $FILES <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>u.", "<cmd>cd $UTILITIES <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>a.", "<cmd>cd $AUTOMATION <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>A.", "<cmd>cd $APPS <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>ml.", "<cmd>cd $MLIBS <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>D", "<cmd>cd ~/Downloads <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>o", "<cmd>cd ~/Documents <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vv", "<cmd>cd ~/Videos <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>wa", "<cmd>cd $WALL <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>wi", "<cmd>cd $WIKI <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>wp", "<cmd>cd $WIKI/personal <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>wS", "<cmd>cd $WIKI/cheatsheets <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>mm", "<cmd>cd ~/Music <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>ca", "<cmd>cd ~/.cache <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>lo", "<cmd>cd ~/.local <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>los", "<cmd>cd ~/.local/share <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>lon", "<cmd>cd ~/.local/share/nvim <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>lop", "<cmd>cd ~/.local/share/nvim/site/pack/packer <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>lob", "<cmd>cd ~/.local/bin <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Re", "<cmd>cd /etc <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>RU", "<cmd>cd /usr <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rus", "<cmd>cd /usr/share <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rub", "<cmd>cd /usr/bin <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rui", "<cmd>cd /usr/include <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rulo", "<cmd>cd /usr/local <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rulob", "<cmd>cd /usr/local/bin <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rulos", "<cmd>cd /usr/local/share <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Ruloi", "<cmd>cd /usr/local/include <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Ruli", "<cmd>cd /usr/lib <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>ex.", "<cmd>cd /opt/exploitdb/exploits <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rv", "<cmd>cd /var <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rb", "<cmd>cd /bin <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rr", "<cmd>cd /root <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Ro", "<cmd>cd /opt <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>Rmn", "<cmd>cd /mnt <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>sc", "<cmd>cd ~/Pictures/screenshots <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vo", "<cmd>cd $VOLUMES <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>vo.", "<cmd>cd $VOLUMES <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>u.", "<cmd>cd $REMOTES <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>an.", "<cmd>cd ~/.local/share/ansible/ <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>P", "<cmd>cd $PROGRAMS/ <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>P.", "<cmd>cd $PROGRAMS/ <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>p", "<cmd>cd $PROJECTS/ <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>p.", "<cmd>cd $PROJECTS/ <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>c.", "<cmd>cd $PLAYGROUND/code/ <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>pp", "<cmd>cd ~/Pictures <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>pl", "<cmd>cd $PLAYGROUND <cr> | <cmd>e .<cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.sf", "<cmd>e ~/.config/shortcuts/sf <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.sd", "<cmd>e ~/.config/shortcuts/sd <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.z", "<cmd>e ~/.config/zsh/.zshrc <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.zp", "<cmd>e ~/.config/zsh/.zprofile <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.p", "<cmd>e ~/.config/picom/picom.conf <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.r", "<cmd>e ~/.config/ranger/rc.conf <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.b", "<cmd>e ~/.bashrc <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.xr", "<cmd>e ~/.Xresources <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.x", "<cmd>e ~/.xprofile <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.t", "<cmd>e ~/.config/tmux/tmux.conf <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.v", "<cmd>e ~/.config/nvim/init.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.l", "<cmd>e .vscode/launch.json <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vv", "<cmd>e ~/.config/nvim/init.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.va", "<cmd>e ~/.config/nvim/lua/config/automation/init.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vs", "<cmd>e ~/.config/nvim/lua/config/settings.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vu", "<cmd>e ~/.config/nvim/lua/utils/lua/telescope.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vk", "<cmd>e ~/.config/nvim/lua/config/keybindings/init.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vK", "<cmd>e ~/.config/nvim/lua/config/keybindings/dap.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vd", "<cmd>e ~/.config/nvim/lua/lsp/dap/dap.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vl", "<cmd>e ~/.config/nvim/lua/lsp/lsp.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vC", "<cmd>e ~/.config/nvim/lua/config/ <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vc", "<cmd>e ~/.config/nvim/lua/core/ <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vp", "<cmd>e ~/.config/nvim/lua/plugins.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.vf", "<cmd>e ~/.config/nvim/lua/lsp/formatters.lua <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.X", "<cmd>e ~/.config/sxhkd/sxhkdrc <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.xm", "<cmd>e ~/.config/xmonad/xmonad.hs <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.xmm", "<cmd>e ~/.config/xmonad/xmonad.hs <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.xmb", "<cmd>e ~/.config/xmobar/xmobarrc <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.n", "<cmd>e ~/.config/newsboat/urls <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.dwm", "<cmd>e $SUCKLESS/dwm/config.h <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.st", "<cmd>e $SUCKLESS/st/config.h <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.a", "<cmd>e ~/.config/.aliases <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.aa", "<cmd>e ~/.config/.aliases <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.ao", "<cmd>e ~/.config/zsh/.aliases <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.K", "<cmd>e $SCRIPTS/apps/qmk/lily58/keymap.c <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.Z", "<cmd>e /root/.config/zsh/.zshrc <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.pr", "<cmd>e $FILES/projections/global/.projections.json <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.s", "<cmd>e $HOME/.ssh/config <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.an", "<cmd>e ~/.local/share/ansible/local.yml <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.anc", "<cmd>e ~/.local/share/ansible/roles/core/tasks/ <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.ant", "<cmd>e ~/.local/share/ansible/tasks/ <cr>", {silent=true, noremap=true})
vim.keymap.set("n", "<localleader>.anT", "<cmd>e ~/.local/share/ansible/TODO <cr>", {silent=true, noremap=true})
