Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"    # Set 2GB RAM
    vb.cpus = 2           # Use 2 CPU cores
  end

  # Disable the GUI mode for VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end
end
