#!/bin/bash

sleep 0.001
. _dgp "$NOTES" "auto update" || f_notes=1
. _dgp "$WIKI" "auto update" || f_wiki=1
. _dgp "$DOTFILES" "auto update" || f_dotfiles=1
. _dgp ~/.local/share/ansible "auto update" || f_ansible=1

clear
echo -e -n "\e[0m"
[[ -z $f_notes ]] && echo -e "\e[35mupdated notes" || echo -e "\e[31mno changes for notes"
[[ -z $f_wiki ]] && echo -e "\e[35mupdated wiki" || echo -e "\e[31mno changes for wiki"
[[ -z $f_dotfiles ]] && echo -e "\e[35mupdated dotfiles" || echo -e "\e[31mno changes for dotfiles"
[[ -z $f_ansible ]] && echo -e "\e[35mupdated ansible" || echo -e "\e[31mno changes for ansible"