#!/bin/bash

# Function to handle git operations for a directory with prompts
dgp_func() {
    local path="$1"

    clear
    pushd "$path" &>/dev/null || return 1
    echo -e "\e[35mIN $(basename "$path" | tr a-z A-Z)"

    changes=$(git status -s)
    if [ -z "$(tr -d '\n' <<< "$changes")" ]; then
        clear
        printf "\e[31mno changes for $(basename "$path")\n"
        popd &>/dev/null || return 1
        return 1
    fi

    git status -s

    printf "\nmessage: \n"
    read -r message

    git add -u

    # If there are untracked files, ask to add them
    if [[ -n "$(git ls-files --other --directory --exclude-standard | head -n 1)" ]]; then
        echo -e "\nadd untracked files? [y/N]"
        read -r untracked

        if [[ "$untracked" == "y" || "$untracked" == "Y" ]]; then
            git add -A
        fi
    fi

    git commit -m "$message"
    git push origin HEAD
    popd &>/dev/null || return
}

sleep 0.001

# Run for each directory
dgp_func "$NOTES" || f_notes=1
dgp_func "$WIKI" || f_wiki=1
dgp_func "$DOTFILES" || f_dotfiles=1
dgp_func ~/.local/share/ansible || f_ansible=1

clear
echo -e -n "\e[0m"
[[ -z $f_notes ]] && echo -e "\e[35mupdated notes" || echo -e "\e[31mno changes for notes"
[[ -z $f_wiki ]] && echo -e "\e[35mupdated wiki" || echo -e "\e[31mno changes for wiki"
[[ -z $f_dotfiles ]] && echo -e "\e[35mupdated dotfiles" || echo -e "\e[31mno changes for dotfiles"
[[ -z $f_ansible ]] && echo -e "\e[35mupdated ansible" || echo -e "\e[31mno changes for ansible"